version: 2

# Ignore ALL secrets in test files and directories
# This prevents false positives from test fixtures/mock data
# while keeping strict detection for production code
paths-ignore:
  - "backend/tests/**"
  - "frontend/tests/**"
  - "**/test_*.py"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/conftest.py"
  - "backend/seed_data.py"  # Demo/seed data only

# DO NOT add matches-ignore here
# We want strict detection everywhere except test paths
