version: '3.8'
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: duotopia
      POSTGRES_USER: duotopia_user
      POSTGRES_PASSWORD: duotopia_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: