"""rename student_id to student_number

Revision ID: 11560478a023
Revises: f66a09eba7e7
Create Date: 2025-09-10 23:28:18.890027

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "11560478a023"
down_revision: Union[str, None] = "f66a09eba7e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
