"""add is_public field to content model

Revision ID: d6854a5f6c92
Revises: ff7fe8ad1faa
Create Date: 2025-08-30 22:15:40.047988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6854a5f6c92'
down_revision: Union[str, None] = 'ff7fe8ad1faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'is_public')
    # ### end Alembic commands ###
