"""fix refunded_amount type to Integer

Revision ID: 289edf7e0aa8
Revises: 62dc946ce341
Create Date: 2025-11-19 19:01:14.090628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "289edf7e0aa8"
down_revision: Union[str, None] = "62dc946ce341"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teacher_subscription_transactions",
        "refunded_amount",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teacher_subscription_transactions",
        "refunded_amount",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
