"""Add teacher subscription transaction model

Revision ID: a3cf45fb8eea
Revises: 75d0959d6f50
Create Date: 2025-09-21 23:45:55.171885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3cf45fb8eea"
down_revision: Union[str, None] = "75d0959d6f50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teacher_subscription_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("TRIAL", "RECHARGE", "EXPIRED", "REFUND", name="transactiontype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("months", sa.Integer(), nullable=False),
        sa.Column("previous_end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_id"),
        "teacher_subscription_transactions",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_id"),
        table_name="teacher_subscription_transactions",
    )
    op.drop_table("teacher_subscription_transactions")
    # ### end Alembic commands ###
