"""add refund tracking fields to transaction

Revision ID: 62dc946ce341
Revises: 59686379aa20
Create Date: 2025-11-19 18:59:35.987653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62dc946ce341"
down_revision: Union[str, None] = "59686379aa20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teacher_subscription_transactions",
        sa.Column("refund_amount", sa.Integer(), nullable=True),
    )
    op.add_column(
        "teacher_subscription_transactions",
        sa.Column("refund_reason", sa.Text(), nullable=True),
    )
    op.add_column(
        "teacher_subscription_transactions",
        sa.Column("refund_notes", sa.Text(), nullable=True),
    )
    op.add_column(
        "teacher_subscription_transactions",
        sa.Column("refund_initiated_by", sa.Integer(), nullable=True),
    )
    op.add_column(
        "teacher_subscription_transactions",
        sa.Column("refund_initiated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_foreign_key(
        None,
        "teacher_subscription_transactions",
        "teachers",
        ["refund_initiated_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teacher_subscription_transactions", type_="foreignkey")
    op.drop_column("teacher_subscription_transactions", "refund_initiated_at")
    op.drop_column("teacher_subscription_transactions", "refund_initiated_by")
    op.drop_column("teacher_subscription_transactions", "refund_notes")
    op.drop_column("teacher_subscription_transactions", "refund_reason")
    op.drop_column("teacher_subscription_transactions", "refund_amount")
    # ### end Alembic commands ###
