"""Add teacher review fields to StudentItemProgress

Revision ID: c6bf62567aa6
Revises: a1b2c3d4e5f6
Create Date: 2025-09-19 23:58:59.675748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6bf62567aa6"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_item_progress",
        sa.Column(
            "teacher_review_score", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
    )
    op.add_column(
        "student_item_progress", sa.Column("teacher_feedback", sa.Text(), nullable=True)
    )
    op.add_column(
        "student_item_progress",
        sa.Column("teacher_reviewed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "student_item_progress", sa.Column("teacher_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "student_item_progress",
        sa.Column("review_status", sa.String(length=20), nullable=True),
    )
    op.create_foreign_key(
        None,
        "student_item_progress",
        "teachers",
        ["teacher_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "student_item_progress", type_="foreignkey")
    op.drop_column("student_item_progress", "review_status")
    op.drop_column("student_item_progress", "teacher_id")
    op.drop_column("student_item_progress", "teacher_reviewed_at")
    op.drop_column("student_item_progress", "teacher_feedback")
    op.drop_column("student_item_progress", "teacher_review_score")
    # ### end Alembic commands ###
