"""add subscription auto_renew and cancelled_at fields

Revision ID: d12004490bb1
Revises: 82d2c62f6175
Create Date: 2025-10-20 15:45:40.441715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d12004490bb1"
down_revision: Union[str, None] = "82d2c62f6175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers", sa.Column("subscription_auto_renew", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "teachers",
        sa.Column(
            "subscription_cancelled_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "subscription_cancelled_at")
    op.drop_column("teachers", "subscription_auto_renew")
    # ### end Alembic commands ###
