"""add_is_active_to_lesson_and_content

Revision ID: 87293915d363
Revises: 624bfd9ff075
Create Date: 2025-09-01 01:16:03.158120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87293915d363'
down_revision: Union[str, None] = '624bfd9ff075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('contents_lesson_id_fkey', 'contents', type_='foreignkey')
    op.create_foreign_key(None, 'contents', 'lessons', ['lesson_id'], ['id'])
    op.add_column('lessons', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint('lessons_program_id_fkey', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'programs', ['program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_program_id_fkey', 'lessons', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lessons', 'is_active')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.create_foreign_key('contents_lesson_id_fkey', 'contents', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.drop_column('contents', 'is_active')
    # ### end Alembic commands ###
