"""Add password reset fields to teacher model

Revision ID: 12578a583628
Revises: a3cf45fb8eea
Create Date: 2025-09-22 08:59:18.690676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12578a583628"
down_revision: Union[str, None] = "a3cf45fb8eea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers",
        sa.Column("password_reset_token", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "teachers",
        sa.Column("password_reset_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "password_reset_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "password_reset_expires_at")
    op.drop_column("teachers", "password_reset_sent_at")
    op.drop_column("teachers", "password_reset_token")
    # ### end Alembic commands ###
