"""Add is_public field to Content model

Revision ID: ff7fe8ad1faa
Revises: 4801201230d2
Create Date: 2025-08-30 19:34:06.736812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7fe8ad1faa'
down_revision: Union[str, None] = '4801201230d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'is_public')
    # ### end Alembic commands ###
