"""remove unused composite indexes

Revision ID: 4566cb74e6f7
Revises: 16ea1d78b460
Create Date: 2025-11-29 22:07:07.132501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4566cb74e6f7"
down_revision: Union[str, None] = "16ea1d78b460"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_classroom_schools_composite", table_name="classroom_schools")
    op.drop_index(
        "ix_teacher_organizations_composite", table_name="teacher_organizations"
    )
    op.drop_index("ix_teacher_schools_composite", table_name="teacher_schools")
    op.drop_index(
        "ix_teacher_schools_permissions_gin",
        table_name="teacher_schools",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_teacher_schools_roles_gin",
        table_name="teacher_schools",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_teacher_schools_roles_gin",
        "teacher_schools",
        ["roles"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_teacher_schools_permissions_gin",
        "teacher_schools",
        ["permissions"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_teacher_schools_composite",
        "teacher_schools",
        ["teacher_id", "school_id"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_organizations_composite",
        "teacher_organizations",
        ["teacher_id", "organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_classroom_schools_composite",
        "classroom_schools",
        ["classroom_id", "school_id"],
        unique=False,
    )
    # ### end Alembic commands ###
