"""initial migration with all tables

Revision ID: 0a46495c9cfc
Revises: 
Create Date: 2025-08-31 00:40:08.483006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a46495c9cfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add level and tags columns to contents table if they don't exist
    op.add_column('contents', sa.Column('level', sa.String(length=10), nullable=True, server_default='A1'))
    op.add_column('contents', sa.Column('tags', sa.JSON(), nullable=True, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
