"""update subscription transaction indexes

Revision ID: 82d2c62f6175
Revises: 5f8acc42934a
Create Date: 2025-10-04 19:49:45.614310

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "82d2c62f6175"
down_revision: Union[str, None] = "5f8acc42934a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tst_created_at", table_name="teacher_subscription_transactions")
    op.drop_index(
        "idx_tst_external_transaction_id",
        table_name="teacher_subscription_transactions",
    )
    op.drop_index(
        "idx_tst_idempotency_key", table_name="teacher_subscription_transactions"
    )
    op.drop_index(
        "idx_tst_payment_provider", table_name="teacher_subscription_transactions"
    )
    op.drop_index("idx_tst_status", table_name="teacher_subscription_transactions")
    op.drop_index(
        "idx_tst_teacher_email", table_name="teacher_subscription_transactions"
    )
    op.drop_constraint(
        "uq_tst_idempotency_key", "teacher_subscription_transactions", type_="unique"
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_external_transaction_id"),
        "teacher_subscription_transactions",
        ["external_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_idempotency_key"),
        "teacher_subscription_transactions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_payment_provider"),
        "teacher_subscription_transactions",
        ["payment_provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_status"),
        "teacher_subscription_transactions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_teacher_email"),
        "teacher_subscription_transactions",
        ["teacher_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_teacher_email"),
        table_name="teacher_subscription_transactions",
    )
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_status"),
        table_name="teacher_subscription_transactions",
    )
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_payment_provider"),
        table_name="teacher_subscription_transactions",
    )
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_idempotency_key"),
        table_name="teacher_subscription_transactions",
    )
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_external_transaction_id"),
        table_name="teacher_subscription_transactions",
    )
    op.create_unique_constraint(
        "uq_tst_idempotency_key",
        "teacher_subscription_transactions",
        ["idempotency_key"],
    )
    op.create_index(
        "idx_tst_teacher_email",
        "teacher_subscription_transactions",
        ["teacher_email"],
        unique=False,
    )
    op.create_index(
        "idx_tst_status", "teacher_subscription_transactions", ["status"], unique=False
    )
    op.create_index(
        "idx_tst_payment_provider",
        "teacher_subscription_transactions",
        ["payment_provider"],
        unique=False,
    )
    op.create_index(
        "idx_tst_idempotency_key",
        "teacher_subscription_transactions",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        "idx_tst_external_transaction_id",
        "teacher_subscription_transactions",
        ["external_transaction_id"],
        unique=False,
    )
    op.create_index(
        "idx_tst_created_at",
        "teacher_subscription_transactions",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
