"""Add organization hierarchy tables

Revision ID: 5106b545b6d2
Revises: 289edf7e0aa8
Create Date: 2025-11-27 00:47:04.724572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5106b545b6d2'
down_revision: Union[str, None] = '289edf7e0aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_table('schools',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_is_active'), 'schools', ['is_active'], unique=False)
    op.create_index(op.f('ix_schools_organization_id'), 'schools', ['organization_id'], unique=False)
    op.create_table('teacher_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'organization_id', name='uq_teacher_organization')
    )
    op.create_index('ix_teacher_organizations_active', 'teacher_organizations', ['teacher_id', 'organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_teacher_organizations_is_active'), 'teacher_organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_teacher_organizations_organization_id'), 'teacher_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_teacher_organizations_teacher_id'), 'teacher_organizations', ['teacher_id'], unique=False)
    op.create_table('classroom_schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('school_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', name='uq_classroom_school')
    )
    op.create_index('ix_classroom_schools_active', 'classroom_schools', ['classroom_id', 'school_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_classroom_schools_classroom_id'), 'classroom_schools', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_schools_is_active'), 'classroom_schools', ['is_active'], unique=False)
    op.create_index(op.f('ix_classroom_schools_school_id'), 'classroom_schools', ['school_id'], unique=False)
    op.create_table('teacher_schools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'school_id', name='uq_teacher_school')
    )
    op.create_index('ix_teacher_schools_active', 'teacher_schools', ['teacher_id', 'school_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_teacher_schools_is_active'), 'teacher_schools', ['is_active'], unique=False)
    op.create_index(op.f('ix_teacher_schools_school_id'), 'teacher_schools', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_schools_teacher_id'), 'teacher_schools', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_schools_teacher_id'), table_name='teacher_schools')
    op.drop_index(op.f('ix_teacher_schools_school_id'), table_name='teacher_schools')
    op.drop_index(op.f('ix_teacher_schools_is_active'), table_name='teacher_schools')
    op.drop_index('ix_teacher_schools_active', table_name='teacher_schools')
    op.drop_table('teacher_schools')
    op.drop_index(op.f('ix_classroom_schools_school_id'), table_name='classroom_schools')
    op.drop_index(op.f('ix_classroom_schools_is_active'), table_name='classroom_schools')
    op.drop_index(op.f('ix_classroom_schools_classroom_id'), table_name='classroom_schools')
    op.drop_index('ix_classroom_schools_active', table_name='classroom_schools')
    op.drop_table('classroom_schools')
    op.drop_index(op.f('ix_teacher_organizations_teacher_id'), table_name='teacher_organizations')
    op.drop_index(op.f('ix_teacher_organizations_organization_id'), table_name='teacher_organizations')
    op.drop_index(op.f('ix_teacher_organizations_is_active'), table_name='teacher_organizations')
    op.drop_index('ix_teacher_organizations_active', table_name='teacher_organizations')
    op.drop_table('teacher_organizations')
    op.drop_index(op.f('ix_schools_organization_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_is_active'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
