"""add_template_and_source_tracking_to_programs

Revision ID: fec3ec42ce70
Revises: 6c42743b461f
Create Date: 2025-09-05 20:08:27.625890

"""

from typing import Sequence, Union  # noqa: F401

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fec3ec42ce70"
down_revision: Union[str, None] = "6c42743b461f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "programs",
        sa.Column("is_template", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "programs", sa.Column("source_type", sa.String(length=20), nullable=True)
    )
    op.add_column("programs", sa.Column("source_metadata", sa.JSON(), nullable=True))
    op.add_column("programs", sa.Column("tags", sa.JSON(), nullable=True))
    op.add_column(
        "programs", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "programs", "classroom_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("programs_classroom_id_fkey", "programs", type_="foreignkey")
    op.create_foreign_key(
        None, "programs", "classrooms", ["classroom_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "programs", type_="foreignkey")
    op.create_foreign_key(
        "programs_classroom_id_fkey", "programs", "classrooms", ["classroom_id"], ["id"]
    )
    op.alter_column(
        "programs", "classroom_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("programs", "deleted_at")
    op.drop_column("programs", "tags")
    op.drop_column("programs", "source_metadata")
    op.drop_column("programs", "source_type")
    op.drop_column("programs", "is_template")
    # ### end Alembic commands ###
