"""add level and tags fields to content model

Revision ID: b5cb932916d6
Revises: d6854a5f6c92
Create Date: 2025-08-31 00:05:26.492550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cb932916d6'
down_revision: Union[str, None] = 'd6854a5f6c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('level', sa.String(length=10), nullable=True, server_default='A1'))
    op.add_column('contents', sa.Column('tags', sa.JSON(), nullable=True, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'tags')
    op.drop_column('contents', 'level')
    # ### end Alembic commands ###
