"""sync model changes (json to jsonb, index names)

Revision ID: b6fb1f60db50
Revises: 09011843bad1
Create Date: 2025-10-22 12:57:43.947022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b6fb1f60db50"
down_revision: Union[str, None] = "09011843bad1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "invoice_status_history",
        "request_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "invoice_status_history",
        "response_payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index("idx_invoice_history_created_at", table_name="invoice_status_history")
    op.drop_index(
        "idx_invoice_history_transaction_id", table_name="invoice_status_history"
    )
    op.create_index(
        op.f("ix_invoice_status_history_created_at"),
        "invoice_status_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_status_history_transaction_id"),
        "invoice_status_history",
        ["transaction_id"],
        unique=False,
    )
    op.alter_column(
        "teacher_subscription_transactions",
        "invoice_response",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(
        "idx_tst_invoice_number", table_name="teacher_subscription_transactions"
    )
    op.drop_index(
        "idx_tst_invoice_status", table_name="teacher_subscription_transactions"
    )
    op.drop_index(
        "idx_tst_rec_invoice_id", table_name="teacher_subscription_transactions"
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_invoice_number"),
        "teacher_subscription_transactions",
        ["invoice_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_invoice_status"),
        "teacher_subscription_transactions",
        ["invoice_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subscription_transactions_rec_invoice_id"),
        "teacher_subscription_transactions",
        ["rec_invoice_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_rec_invoice_id"),
        table_name="teacher_subscription_transactions",
    )
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_invoice_status"),
        table_name="teacher_subscription_transactions",
    )
    op.drop_index(
        op.f("ix_teacher_subscription_transactions_invoice_number"),
        table_name="teacher_subscription_transactions",
    )
    op.create_index(
        "idx_tst_rec_invoice_id",
        "teacher_subscription_transactions",
        ["rec_invoice_id"],
        unique=False,
    )
    op.create_index(
        "idx_tst_invoice_status",
        "teacher_subscription_transactions",
        ["invoice_status"],
        unique=False,
    )
    op.create_index(
        "idx_tst_invoice_number",
        "teacher_subscription_transactions",
        ["invoice_number"],
        unique=False,
    )
    op.alter_column(
        "teacher_subscription_transactions",
        "invoice_response",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_invoice_status_history_transaction_id"),
        table_name="invoice_status_history",
    )
    op.drop_index(
        op.f("ix_invoice_status_history_created_at"),
        table_name="invoice_status_history",
    )
    op.create_index(
        "idx_invoice_history_transaction_id",
        "invoice_status_history",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "idx_invoice_history_created_at",
        "invoice_status_history",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "invoice_status_history",
        "response_payload",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "invoice_status_history",
        "request_payload",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
