"""Make school_id nullable and add multi-role support

Revision ID: 47165cdabd82
Revises: af563d6729f2
Create Date: 2025-08-20 21:19:15.886809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47165cdabd82'
down_revision: Union[str, None] = 'af563d6729f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_individual_teacher', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_institutional_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('current_role_context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_role_context')
    op.drop_column('users', 'is_institutional_admin')
    op.drop_column('users', 'is_individual_teacher')
    # ### end Alembic commands ###
