"""sync quota models with codebase changes

Revision ID: f42b27a78bec
Revises: 83420cb2e590
Create Date: 2025-11-05 06:08:24.435381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f42b27a78bec"
down_revision: Union[str, None] = "83420cb2e590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "point_usage_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_point_usage_logs_created_at", table_name="point_usage_logs")
    op.drop_index("ix_point_usage_logs_student_id", table_name="point_usage_logs")
    op.drop_index(
        "ix_point_usage_logs_subscription_period_id", table_name="point_usage_logs"
    )
    op.drop_index("ix_point_usage_logs_teacher_id", table_name="point_usage_logs")
    op.create_index(
        op.f("ix_point_usage_logs_id"), "point_usage_logs", ["id"], unique=False
    )
    op.alter_column(
        "subscription_periods",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_subscription_periods_dates", table_name="subscription_periods")
    op.drop_index("ix_subscription_periods_status", table_name="subscription_periods")
    op.drop_index(
        "ix_subscription_periods_teacher_id", table_name="subscription_periods"
    )
    op.create_index(
        op.f("ix_subscription_periods_id"), "subscription_periods", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_periods_id"), table_name="subscription_periods")
    op.create_index(
        "ix_subscription_periods_teacher_id",
        "subscription_periods",
        ["teacher_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_periods_status",
        "subscription_periods",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_periods_dates",
        "subscription_periods",
        ["start_date", "end_date"],
        unique=False,
    )
    op.alter_column(
        "subscription_periods",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_point_usage_logs_id"), table_name="point_usage_logs")
    op.create_index(
        "ix_point_usage_logs_teacher_id",
        "point_usage_logs",
        ["teacher_id"],
        unique=False,
    )
    op.create_index(
        "ix_point_usage_logs_subscription_period_id",
        "point_usage_logs",
        ["subscription_period_id"],
        unique=False,
    )
    op.create_index(
        "ix_point_usage_logs_student_id",
        "point_usage_logs",
        ["student_id"],
        unique=False,
    )
    op.create_index(
        "ix_point_usage_logs_created_at",
        "point_usage_logs",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "point_usage_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
